keys:
  - &mmit FECD0B179B7700732C2A989126727003542EA506
  - &apq-pc age1nk6m3d4jrcxqa9e5k4w69vvama0a3xmz3hvckfd9vyu633j9254qw7jlkp
  - &xps5960 age1jwe5fxz9e6jvlmc399je957k3a3yynvu7yd3j827hhtz4swjedls9lfryj
creation_rules:
  - path_regex: hosts/common/secrets.yaml
    key_groups:
      - age:
        - *apq-pc
        - *xps5960


